export const schemaSql = [
  `CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(64) NULL UNIQUE,
    display_name VARCHAR(80) NOT NULL,
    avatar_url TEXT NULL,
    default_address_label TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_active_at DATETIME NULL,
    deleted_at DATETIME NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS auth_accounts (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    provider_user_id VARCHAR(128) NOT NULL,
    password_hash VARCHAR(255) NULL,
    bound_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    UNIQUE KEY uk_provider_user (provider, provider_user_id),
    KEY idx_auth_user (user_id),
    CONSTRAINT fk_auth_user FOREIGN KEY (user_id) REFERENCES users(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS categories (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(80) NOT NULL UNIQUE,
    icon VARCHAR(20) NOT NULL,
    description VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS merchants (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(30) NOT NULL,
    logo_url TEXT NOT NULL,
    rating DECIMAL(3,2) NOT NULL DEFAULT 4.80,
    delivery_minutes INT NOT NULL DEFAULT 40,
    min_order_amount INT NOT NULL DEFAULT 0,
    delivery_fee INT NOT NULL DEFAULT 0,
    tags JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_merchant_type (type)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS media_assets (
    id VARCHAR(36) PRIMARY KEY,
    source_provider VARCHAR(80) NOT NULL,
    source_asset_id VARCHAR(128) NOT NULL,
    license_type VARCHAR(80) NOT NULL,
    license_url TEXT NULL,
    license_start_at DATETIME NULL,
    license_end_at DATETIME NULL,
    file_url TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    usage_scope VARCHAR(80) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS products (
    id VARCHAR(36) PRIMARY KEY,
    merchant_id VARCHAR(36) NOT NULL,
    category_id VARCHAR(36) NOT NULL,
    order_type VARCHAR(30) NOT NULL,
    title VARCHAR(160) NOT NULL,
    subtitle VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT NOT NULL,
    virtual_price INT NOT NULL,
    compare_at_price INT NOT NULL,
    virtual_stock INT NOT NULL DEFAULT 999,
    virtual_sales_count INT NOT NULL DEFAULT 0,
    tags JSON NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    recommendation_weight INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_products_category (category_id),
    KEY idx_products_merchant (merchant_id),
    KEY idx_products_type_status (order_type, status),
    FULLTEXT KEY ft_products_title (title, subtitle, description),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_product_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS carts (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS coupon_templates (
    id VARCHAR(36) PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(255) NOT NULL,
    scope VARCHAR(30) NOT NULL DEFAULT 'all',
    threshold_amount INT NOT NULL DEFAULT 0,
    discount_amount INT NOT NULL,
    total_quantity INT NULL,
    claimed_count INT NOT NULL DEFAULT 0,
    per_user_limit INT NOT NULL DEFAULT 1,
    starts_at DATETIME NOT NULL,
    ends_at DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_coupon_templates_status_time (status, starts_at, ends_at),
    KEY idx_coupon_templates_scope (scope)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS cart_items (
    id VARCHAR(36) PRIMARY KEY,
    cart_id VARCHAR(36) NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cart_product (cart_id, product_id),
    KEY idx_cart_items_cart (cart_id),
    CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) REFERENCES products(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(36) PRIMARY KEY,
    order_no VARCHAR(40) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    order_type VARCHAR(30) NOT NULL,
    status VARCHAR(40) NOT NULL,
    original_amount INT NOT NULL DEFAULT 0,
    total_virtual_amount INT NOT NULL,
    saved_amount INT NOT NULL,
    coupon_id VARCHAR(36) NULL,
    coupon_template_id VARCHAR(36) NULL,
    coupon_name VARCHAR(120) NULL,
    coupon_discount_amount INT NOT NULL DEFAULT 0,
    item_count INT NOT NULL,
    virtual_payment_method VARCHAR(60) NOT NULL,
    virtual_address_label TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    canceled_at DATETIME NULL,
    KEY idx_orders_user_created (user_id, created_at),
    KEY idx_orders_status (status),
    KEY idx_orders_type (order_type),
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS user_coupons (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    template_id VARCHAR(36) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'available',
    claimed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at DATETIME NULL,
    expires_at DATETIME NOT NULL,
    order_id VARCHAR(36) NULL,
    UNIQUE KEY uk_user_coupon (user_id, template_id, id),
    KEY idx_user_coupons_user_status (user_id, status, expires_at),
    KEY idx_user_coupons_template (template_id),
    KEY idx_user_coupons_order (order_id),
    CONSTRAINT fk_user_coupon_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_coupon_template FOREIGN KEY (template_id) REFERENCES coupon_templates(id),
    CONSTRAINT fk_user_coupon_order FOREIGN KEY (order_id) REFERENCES orders(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS order_items (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    title VARCHAR(160) NOT NULL,
    image_url TEXT NOT NULL,
    unit_price INT NOT NULL,
    quantity INT NOT NULL,
    subtotal_amount INT NOT NULL,
    category_id VARCHAR(36) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_order_items_order (order_id),
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES products(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS order_status_events (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    from_status VARCHAR(40) NULL,
    to_status VARCHAR(40) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(255) NOT NULL,
    trigger_type VARCHAR(40) NOT NULL,
    job_id VARCHAR(80) NULL,
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata JSON NULL,
    KEY idx_order_status_events_order (order_id, occurred_at),
    CONSTRAINT fk_order_status_event_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS order_reviews (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    rating TINYINT NOT NULL,
    content TEXT NOT NULL,
    tags JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_order_reviews_order (order_id),
    KEY idx_order_reviews_user_created (user_id, created_at),
    KEY idx_order_reviews_rating (rating),
    CONSTRAINT fk_order_review_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_review_user FOREIGN KEY (user_id) REFERENCES users(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS behavior_events (
    id VARCHAR(36) PRIMARY KEY,
    event_name VARCHAR(80) NOT NULL,
    user_id VARCHAR(36) NULL,
    anonymous_id VARCHAR(80) NULL,
    session_id VARCHAR(80) NOT NULL,
    platform VARCHAR(30) NOT NULL,
    page_path VARCHAR(255) NULL,
    referrer VARCHAR(255) NULL,
    occurred_at DATETIME NOT NULL,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    app_version VARCHAR(40) NULL,
    device_info JSON NULL,
    network_type VARCHAR(40) NULL,
    experiment_id VARCHAR(80) NULL,
    properties JSON NOT NULL,
    KEY idx_behavior_name_time (event_name, occurred_at),
    KEY idx_behavior_user_time (user_id, occurred_at),
    KEY idx_behavior_session (session_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS savings_opportunity_records (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    session_id VARCHAR(80) NOT NULL,
    source_type VARCHAR(60) NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    category_id VARCHAR(36) NOT NULL,
    order_type VARCHAR(30) NOT NULL,
    virtual_amount INT NOT NULL,
    dedupe_key VARCHAR(180) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'counted',
    occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    counted_at DATETIME NULL,
    UNIQUE KEY uk_savings_dedupe (dedupe_key),
    KEY idx_savings_user_status (user_id, status, occurred_at),
    CONSTRAINT fk_savings_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_savings_product FOREIGN KEY (product_id) REFERENCES products(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS admin_users (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at DATETIME NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS operation_logs (
    id VARCHAR(36) PRIMARY KEY,
    admin_user_id VARCHAR(36) NULL,
    action VARCHAR(120) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id VARCHAR(80) NULL,
    detail JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_operation_logs_created (created_at)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`
]
